// Simple dictionary-based i18n (English / বাংলা). Keys are the English source strings.
//   t('Good morning, {name}', { name })   -> text for the active language
//   tb(text)                              -> translate sentences that come from the backend (plan reasons, drivers, ...)
// Numbers stay in Latin digits; the taka sign ৳ is used everywhere.
const KEY = 'rw-lang'

let current = 'en'
try { if (localStorage.getItem(KEY) === 'bn') current = 'bn' } catch { /* storage blocked: stay on English */ }
if (typeof document !== 'undefined') document.documentElement.lang = current

export const getLang = () => current
export const setLang = (l) => {
  current = l === 'bn' ? 'bn' : 'en'
  try { localStorage.setItem(KEY, current) } catch { /* ignore */ }
  if (typeof document !== 'undefined') document.documentElement.lang = current
}
// Latin digits in both languages so figures read the same everywhere.
export const locale = () => (current === 'bn' ? 'bn-BD-u-nu-latn' : 'en-GB')

const fill = (s, vars) => (vars ? s.replace(/\{(\w+)\}/g, (_, k) => (vars[k] ?? '')) : s)

export function t(en, vars) {
  if (en == null) return ''
  const s = current === 'bn' ? (BN[en] ?? en) : en
  return fill(s, vars)
}

const MONTHS = { Jan: 'জানুয়ারি', Feb: 'ফেব্রুয়ারি', Mar: 'মার্চ', Apr: 'এপ্রিল', May: 'মে', Jun: 'জুন', Jul: 'জুলাই', Aug: 'আগস্ট', Sep: 'সেপ্টেম্বর', Oct: 'অক্টোবর', Nov: 'নভেম্বর', Dec: 'ডিসেম্বর' }
const dateBn = (iso) => {
  const d = new Date(iso + 'T00:00:00')
  return Number.isNaN(+d) ? iso : d.toLocaleDateString(locale(), { day: 'numeric', month: 'short' })
}

// [pattern, builder] for sentences generated by the backend with numbers inside.
const RULES = [
  [/^Bills and EMIs due before the next transfer need about ([\d,]+); ([\d,]+) is added to the bill vault so they are paid on time\.$/, (m) => `পরবর্তী ট্রান্সফারের আগে বিল ও কিস্তির জন্য প্রায় ${m[1]} লাগবে; সময়মতো পরিশোধের জন্য বিল ভল্টে ${m[2]} জমা হচ্ছে।`],
  [/^Next transfer is expected in (\d+) days \(could be as late as (\d+)\)\. We reserve money for about (\d+) days of essentials\.$/, (m) => `পরবর্তী ট্রান্সফার প্রায় ${m[1]} দিনের মধ্যে আসার কথা (দেরি হলে ${m[2]} দিন পর্যন্ত হতে পারে)। তাই প্রায় ${m[3]} দিনের প্রয়োজনীয় খরচের জন্য টাকা আলাদা রাখা হচ্ছে।`],
  [/^Part of the surplus builds your emergency buffer toward ([\d.]+) month of needs\.$/, (m) => `উদ্বৃত্তের একটি অংশ আপনার জরুরি তহবিলকে ${m[1]} মাসের খরচের লক্ষ্যে এগিয়ে নেয়।`],
  [/^Spending in the last week is (\d+)% above usual\.$/, (m) => `গত সপ্তাহের খরচ স্বাভাবিকের চেয়ে ${m[1]}% বেশি।`],
  [/^The next transfer is about (\d+) days later than usual\.$/, (m) => `পরবর্তী ট্রান্সফার স্বাভাবিকের চেয়ে প্রায় ${m[1]} দিন দেরিতে আসছে।`],
  [/^Current money covers about (\d+) days, but the next transfer is expected in about (\d+) days\.$/, (m) => `বর্তমান টাকায় প্রায় ${m[1]} দিন চলবে, কিন্তু পরবর্তী ট্রান্সফার আসতে প্রায় ${m[2]} দিন লাগতে পারে।`],
  [/^Eid spending: daily needs are about (\d+)% higher until (\d{4}-\d{2}-\d{2})\.$/, (m) => `ঈদের খরচ: ${dateBn(m[2])} পর্যন্ত দৈনিক প্রয়োজন প্রায় ${m[1]}% বেশি।`],
  [/^Unexpected medical expense of ৳([\d,]+) recently\.$/, (m) => `সম্প্রতি ৳${m[1]} অপ্রত্যাশিত চিকিৎসা খরচ হয়েছে।`],
  [/^You may run short about (\d+) days before your next transfer\.$/, (m) => `পরবর্তী ট্রান্সফারের আগে প্রায় ${m[1]} দিন টাকা কম পড়তে পারে।`],
  [/^Spend about ৳([\d,]+) less per day$/, (m) => `দিনে প্রায় ৳${m[1]} কম খরচ করুন`],
  [/^Move ৳([\d,]+) from goal savings$/, (m) => `লক্ষ্যের সঞ্চয় থেকে ৳${m[1]} সরান`],
  [/^Ask (.+) to send by (\d{1,2}) ([A-Z][a-z]{2})$/, (m) => `${m[1]}-কে ${m[2]} ${MONTHS[m[3]] || m[3]}-এর মধ্যে পাঠাতে বলুন`],
  [/^Ask (.+) for an earlier transfer$/, (m) => `${m[1]}-কে আগে টাকা পাঠাতে বলুন`],
  [/^We will show (.+) a gentle note\. They decide\.$/, (m) => `আমরা ${m[1]}-কে একটি নম্র বার্তা দেখাব। সিদ্ধান্ত তাঁর।`],
  [/^([\d.]+)x your usual amount \(estimate ([\d,]+)\)$/, (m) => `স্বাভাবিক পরিমাণের ${m[1]} গুণ (অনুমান ${m[2]})`],
  [/^At your current pace, about (\d+) months$/, (m) => `বর্তমান গতিতে প্রায় ${m[1]} মাস`],
  [/^Family · (.+)$/, (m) => `পরিবার · ${m[1]}`],
  [/^Sender · (.+)$/, (m) => `প্রেরক · ${m[1]}`],
]

const BACKEND = {
  Conservative: 'সতর্ক', Balanced: 'সুষম', 'Goal-focused': 'লক্ষ্যকেন্দ্রিক', 'Your edit': 'আপনার সম্পাদনা',
  'Money you already have in hand is counted before adding more to needs.': 'হাতে থাকা টাকা আগে হিসাবে ধরা হয়, তারপর দৈনিক খরচে আরও যোগ করা হয়।',
  'Goals are funded by priority and how close the deadline is.': 'অগ্রাধিকার ও সময়সীমা কত কাছে তার ভিত্তিতে লক্ষ্যগুলোতে টাকা দেওয়া হয়।',
  'Extra money not needed for goals is kept as savings.': 'লক্ষ্যের জন্য প্রয়োজন নেই এমন বাড়তি টাকা সঞ্চয়ে রাখা হয়।',
  'Edited by the family.': 'পরিবার নিজে সম্পাদনা করেছে।',
  'This keeps your money lasting until the transfer arrives.': 'এতে ট্রান্সফার আসা পর্যন্ত আপনার টাকা চলবে।',
  'Your goals stay yours; you can top them up from the next transfer.': 'লক্ষ্যগুলো আপনারই থাকবে; পরের ট্রান্সফার থেকে আবার যোগ করতে পারবেন।',
  'A large one-off expense happened recently.': 'সম্প্রতি একটি বড় অপ্রত্যাশিত খরচ হয়েছে।',
  'Delay non-essential spending for a few days.': 'অপ্রয়োজনীয় খরচ কয়েক দিন পিছিয়ে দিন।',
  'Consider using your emergency buffer only for essentials.': 'জরুরি তহবিল শুধু প্রয়োজনীয় খরচের জন্য ব্যবহার করুন।',
  'Ask your sender whether the transfer date has changed.': 'ট্রান্সফারের তারিখ বদলেছে কি না প্রেরককে জিজ্ঞাসা করুন।',
  'Estimate based on the same month last year': 'গত বছরের একই মাসের ভিত্তিতে অনুমান',
  'Goal reached': 'লক্ষ্য পূরণ হয়েছে', 'Accept a plan to see a pace estimate': 'গতির অনুমান দেখতে একটি পরিকল্পনা গ্রহণ করুন',
  'No contributions yet': 'এখনও কোনো জমা নেই',
  'This goal needs a large share of each transfer; consider a longer deadline.': 'এই লক্ষ্যে প্রতিটি ট্রান্সফারের বড় অংশ লাগবে; সময়সীমা বাড়ানোর কথা ভাবুন।',
  'Half of your expected monthly surplus, so there is room for surprises.': 'আপনার প্রত্যাশিত মাসিক উদ্বৃত্তের অর্ধেক, যাতে অপ্রত্যাশিত খরচের জায়গা থাকে।',
  'The family has not shared goal progress with you yet.': 'পরিবার এখনও আপনার সঙ্গে লক্ষ্যের অগ্রগতি শেয়ার করেনি।',
  "The family's forecast now reflects your planned transfer (a heuristic, not a promise).": 'পরিবারের পূর্বাভাসে এখন আপনার পরিকল্পিত ট্রান্সফার ধরা হয়েছে (এটি একটি আনুমানিক হিসাব, প্রতিশ্রুতি নয়)।',
  'generated explanation': 'তৈরি করা ব্যাখ্যা',
  Electricity: 'বিদ্যুৎ', Gas: 'গ্যাস', Internet: 'ইন্টারনেট', 'Phone EMI': 'ফোনের কিস্তি', 'Motorcycle EMI': 'মোটরসাইকেলের কিস্তি',
  'School fees': 'স্কুলের ফি', 'House repair': 'বাড়ি মেরামত', 'Education fund': 'শিক্ষা তহবিল', Water: 'পানি', Rent: 'বাড়িভাড়া',
}

export function tb(text) {
  if (text == null) return ''
  if (current !== 'bn') return text
  if (BN[text]) return BN[text]
  if (BACKEND[text]) return BACKEND[text]
  for (const [re, build] of RULES) {
    const m = re.exec(text)
    if (m) return build(m)
  }
  return text
}

const BN = {
  // phone verification and password reset
  'Demo: no SMS is sent.': 'ডেমো: কোনো এসএমএস পাঠানো হয় না।', 'Your code:': 'আপনার কোড:', 'Verify your phone': 'আপনার ফোন যাচাই করুন',
  '{name}, add your mobile number so you can recover your account and get important alerts.': '{name}, আপনার মোবাইল নম্বর যোগ করুন, যাতে অ্যাকাউন্ট পুনরুদ্ধার করতে পারেন এবং জরুরি বার্তা পান।',
  'Mobile number': 'মোবাইল নম্বর', 'Send code': 'কোড পাঠান', '6-digit code': '৬ সংখ্যার কোড', 'The code works for 5 minutes and allows 5 tries.': 'কোডটি ৫ মিনিট কাজ করবে এবং ৫ বার চেষ্টা করা যাবে।',
  'Verify phone': 'ফোন যাচাই করুন', 'Use a different number or resend': 'অন্য নম্বর দিন অথবা আবার পাঠান', 'Reset your password': 'পাসওয়ার্ড রিসেট করুন',
  'Password changed. Sign in with your new password.': 'পাসওয়ার্ড বদলেছে। নতুন পাসওয়ার্ড দিয়ে সাইন-ইন করুন।', 'Back to sign in': 'সাইন-ইনে ফিরুন',
  'Enter the email or verified mobile number of your account. We will send a 6-digit code.': 'আপনার অ্যাকাউন্টের ইমেইল বা যাচাই করা মোবাইল নম্বর দিন। আমরা একটি ৬ সংখ্যার কোড পাঠাব।',
  'Email or mobile number': 'ইমেইল বা মোবাইল নম্বর', 'If an account matches, a code has been sent.': 'কোনো অ্যাকাউন্ট মিললে একটি কোড পাঠানো হয়েছে।',
  'New password (at least 8 characters)': 'নতুন পাসওয়ার্ড (কমপক্ষে ৮ অক্ষর)', 'Changing your password signs you out everywhere.': 'পাসওয়ার্ড বদলালে সব জায়গা থেকে আপনি সাইন-আউট হয়ে যাবেন।',
  'Change password': 'পাসওয়ার্ড বদলান', 'Forgot password?': 'পাসওয়ার্ড ভুলে গেছেন?',
  // navigation and roles
  'Waking up the server…': 'সার্ভার জাগানো হচ্ছে…',
  'The free demo server sleeps when idle. The first load can take up to a minute. We will open the app as soon as it is ready.': 'বিনামূল্যের ডেমো সার্ভার অলস থাকলে ঘুমিয়ে পড়ে। প্রথমবার চালু হতে এক মিনিট পর্যন্ত লাগতে পারে। প্রস্তুত হলেই আমরা অ্যাপ খুলে দেব।',
  'Still trying… (attempt {n})': 'এখনও চেষ্টা চলছে… (প্রচেষ্টা {n})',
  'Retry now': 'এখনই আবার চেষ্টা করুন',
  'for upay': 'উপায়-এর জন্য',
  Home: 'হোম', Payments: 'পেমেন্ট', Plan: 'পরিকল্পনা', Goals: 'লক্ষ্য', Insights: 'অন্তর্দৃষ্টি',
  'Family wallet': 'পারিবারিক ওয়ালেট', 'Sender abroad': 'প্রবাসী প্রেরক', Administrator: 'অ্যাডমিনিস্ট্রেটর', Family: 'পরিবার',
  'I receive money from a relative abroad': 'আমি বিদেশ থেকে আত্মীয়ের পাঠানো টাকা পাই', 'I send money home': 'আমি দেশে টাকা পাঠাই',
  'Admin console': 'অ্যাডমিন কনসোল', 'Log out': 'লগ আউট', 'Loading…': 'লোড হচ্ছে…', 'Waiting for the API…': 'সার্ভারের অপেক্ষায়…',
  'Try again': 'আবার চেষ্টা করুন', 'You are still signed in. Your data is safe on the server.': 'আপনি এখনও সাইন-ইন আছেন। আপনার তথ্য সার্ভারে নিরাপদ আছে।',
  'Signed in as': 'সাইন-ইন করা আছে:', 'Demo clock': 'ডেমো ঘড়ি', 'Trigger remittance': 'রেমিট্যান্স আসুক', '+1 day': '+১ দিন', '+7 days': '+৭ দিন',
  'Previewing a demo household': 'একটি ডেমো পরিবার দেখা হচ্ছে', 'Preview sender view →': 'প্রেরকের দৃশ্য দেখুন →', 'Back to admin console →': 'অ্যাডমিন কনসোলে ফিরুন →',
  'Synthetic data only. No real money or customer data.': 'শুধু কৃত্রিম তথ্য। কোনো আসল টাকা বা গ্রাহকের তথ্য নেই।',
  'Synthetic data only. No real money moves.': 'শুধু কৃত্রিম তথ্য। কোনো আসল টাকা নড়ে না।',
  Close: 'বন্ধ করুন', 'Why?': 'কেন?', 'Why this estimate?': 'এই অনুমান কেন?',
  // AI badges
  'AI estimate': 'এআই অনুমান', 'AI plan': 'এআই পরিকল্পনা', 'AI summary': 'এআই সারসংক্ষেপ', 'AI suggestion': 'এআই পরামর্শ', 'AI forecast': 'এআই পূর্বাভাস',
  Estimate: 'অনুমান', Explanation: 'ব্যাখ্যা', 'Top reasons': 'প্রধান কারণ', Simulated: 'সিমুলেটেড',
  'How this is worked out': 'এটি কীভাবে হিসাব করা হয়', 'How to read this': 'এটি কীভাবে পড়বেন', 'About these categories': 'এই ক্যাটাগরি সম্পর্কে',
  'AI estimate for {m}': '{m} মাসের জন্য এআই অনুমান',
  'AI values are estimates. All amounts are calculated in code; the AI only explains them.': 'এআই-এর মানগুলো অনুমান। সব অঙ্ক কোড দিয়ে হিসাব করা; এআই শুধু ব্যাখ্যা করে।',
  'Generated from computed numbers only. Predictions are marked as estimates.': 'শুধু হিসাব করা সংখ্যা থেকে তৈরি। পূর্বাভাসগুলো অনুমান হিসেবে চিহ্নিত।',
  'Show the facts used': 'ব্যবহৃত তথ্য দেখুন', 'Hide the facts used': 'ব্যবহৃত তথ্য লুকান',
  // status chips
  Scheduled: 'নির্ধারিত', Paid: 'পরিশোধিত', 'Needs review': 'যাচাই দরকার', 'At risk': 'ঝুঁকিতে', Overdue: 'মেয়াদোত্তীর্ণ',
  // categories and forecast features
  'Food & groceries': 'খাবার ও মুদি', 'Bills & EMI': 'বিল ও কিস্তি', Education: 'শিক্ষা', Transport: 'যাতায়াত', Health: 'স্বাস্থ্য', Other: 'অন্যান্য',
  'Usual gap between transfers': 'ট্রান্সফারের মধ্যে স্বাভাবিক ব্যবধান', 'Recent gap between transfers': 'সাম্প্রতিক ট্রান্সফারের ব্যবধান',
  'Last gap between transfers': 'শেষ ট্রান্সফারের ব্যবধান', 'How much the gap varies': 'ব্যবধান কতটা বদলায়', 'Past transfers that were late': 'আগের দেরিতে আসা ট্রান্সফার',
  'Eid timing': 'ঈদের সময়', 'Eid within a month': 'এক মাসের মধ্যে ঈদ', 'Latest transfer amount': 'সর্বশেষ ট্রান্সফারের পরিমাণ',
  'Recent transfer amounts': 'সাম্প্রতিক ট্রান্সফারের পরিমাণ', 'Usual transfer amount': 'স্বাভাবিক ট্রান্সফারের পরিমাণ', 'How much amounts vary': 'পরিমাণ কতটা বদলায়',
  'Day of the month': 'মাসের দিন', 'Time of year': 'বছরের সময়', 'Length of history': 'তথ্যের দৈর্ঘ্য', 'Local income': 'স্থানীয় আয়',
  'Household size': 'পরিবারের আকার', 'Rural or urban': 'গ্রাম না শহর',
  high: 'উচ্চ', medium: 'মাঝারি', low: 'কম',
  // charts
  Today: 'আজ', 'Next transfer': 'পরবর্তী ট্রান্সফার', 'Forecast range': 'পূর্বাভাসের পরিসর', 'Most likely': 'সম্ভাব্য', 'Below zero': 'শূন্যের নিচে',
  '● Dots = EMI and bill payments · Red dashed line = zero balance · Shaded = forecast range': '● বিন্দু = কিস্তি ও বিল পরিশোধ · লাল ড্যাশ রেখা = শূন্য ব্যালেন্স · ছায়া = পূর্বাভাসের পরিসর',
  'Balance may drop below zero around {d}': '{d} নাগাদ ব্যালেন্স শূন্যের নিচে নামতে পারে', ' if the transfer comes late.': ' যদি ট্রান্সফার দেরিতে আসে।',
  'Balance is expected to stay above zero until your next transfer.': 'পরবর্তী ট্রান্সফার পর্যন্ত ব্যালেন্স শূন্যের ওপরে থাকার আশা করা হচ্ছে।',
  'Available once a forecast exists.': 'পূর্বাভাস তৈরি হলে এটি পাওয়া যাবে।',
  // sign in
  'Sign in': 'সাইন-ইন', 'Create account': 'অ্যাকাউন্ট খুলুন', 'I am a…': 'আমি একজন…', 'Your name': 'আপনার নাম', Email: 'ইমেইল', Password: 'পাসওয়ার্ড',
  ' (at least 8 characters)': ' (কমপক্ষে ৮ অক্ষর)', 'Family invite code': 'পরিবারের আমন্ত্রণ কোড', 'Ask your family for the code shown in their app (Goals → Sharing).': 'পরিবারের অ্যাপে (লক্ষ্য → শেয়ারিং) দেখানো কোডটি তাদের কাছ থেকে নিন।',
  'Where does your sender work? (optional)': 'আপনার প্রেরক কোথায় কাজ করেন? (ঐচ্ছিক)', 'e.g. Dubai': 'যেমন: দুবাই', 'Please wait…': 'অপেক্ষা করুন…',
  'Create {role} account': '{role} অ্যাকাউন্ট খুলুন', 'Just looking? Try a demo account (synthetic data):': 'শুধু দেখতে চান? একটি ডেমো অ্যাকাউন্ট চেষ্টা করুন (কৃত্রিম তথ্য):',
  'Platform staff sign in here too: the app opens the admin console for administrator accounts.': 'প্ল্যাটফর্মের কর্মীরাও এখানে সাইন-ইন করেন: অ্যাডমিন অ্যাকাউন্টে অ্যাপ অ্যাডমিন কনসোল খোলে।',
  'By continuing you agree this is a hackathon prototype. No real money, customer data or banking is involved.': 'চালিয়ে গেলে আপনি মেনে নিচ্ছেন যে এটি একটি হ্যাকাথন প্রোটোটাইপ। এতে কোনো আসল টাকা, গ্রাহকের তথ্য বা ব্যাংকিং জড়িত নয়।',
  'Make every remittance last until the next one.': 'প্রতিটি রেমিট্যান্স যেন পরের রেমিট্যান্স আসা পর্যন্ত চলে।',
  'An AI planner for families who live on money sent from abroad: it forecasts the next transfer, keeps bills paid on time, warns early about shortfalls, and shares progress with the sender only if the family chooses.': 'বিদেশ থেকে পাঠানো টাকার ওপর নির্ভরশীল পরিবারের জন্য একটি এআই পরিকল্পনাকারী: এটি পরবর্তী ট্রান্সফারের পূর্বাভাস দেয়, বিল সময়মতো পরিশোধ নিশ্চিত করে, ঘাটতির আগে সতর্ক করে, এবং পরিবার চাইলেই কেবল প্রেরকের সঙ্গে অগ্রগতি শেয়ার করে।',
  'The family always decides. The AI only suggests.': 'সিদ্ধান্ত সবসময় পরিবারের। এআই শুধু পরামর্শ দেয়।',
  'Senders see goal progress only, never spending, unless the family shares more.': 'পরিবার আরও শেয়ার না করলে প্রেরক শুধু লক্ষ্যের অগ্রগতি দেখেন, খরচ কখনও নয়।',
  // home
  'Good morning, {name}': 'শুভ সকাল, {name}', '+ Add payment': '+ পেমেন্ট যোগ করুন', 'Available balance': 'উপলব্ধ ব্যালেন্স',
  '{amt} reserved for bills & EMI': 'বিল ও কিস্তির জন্য {amt} সংরক্ষিত', 'Next remittance': 'পরবর্তী রেমিট্যান্স',
  'Expected in {a}–{b} days': '{a}–{b} দিনের মধ্যে আসার কথা', 'About {a} – {b} from {who} ({city})': '{who}-এর কাছ থেকে প্রায় {a} – {b} ({city})',
  'Confidence: {c}': 'নির্ভরযোগ্যতা: {c}', ' · overdue, range widened': ' · দেরি হচ্ছে, পরিসর বাড়ানো হয়েছে', 'Collecting more history…': 'আরও তথ্য সংগ্রহ হচ্ছে…',
  'Safe to spend': 'নিরাপদে খরচযোগ্য', '/ day': '/ দিন',
  'Until your next expected transfer (about {n} days), without missing any bill. You usually spend about {amt} a day.': 'পরবর্তী প্রত্যাশিত ট্রান্সফার (প্রায় {n} দিন) পর্যন্ত, কোনো বিল না ছেড়ে। আপনি সাধারণত দিনে প্রায় {amt} খরচ করেন।',
  'Heads up: you may run short about {n} day before your next transfer.': 'সতর্কতা: পরবর্তী ট্রান্সফারের আগে প্রায় {n} দিন টাকা কম পড়তে পারে।',
  'Heads up: you may run short about {n} days before your next transfer.': 'সতর্কতা: পরবর্তী ট্রান্সফারের আগে প্রায় {n} দিন টাকা কম পড়তে পারে।',
  'See options →': 'বিকল্প দেখুন →', 'Projected balance until next transfer': 'পরবর্তী ট্রান্সফার পর্যন্ত সম্ভাব্য ব্যালেন্স', 'Upcoming payments': 'আসন্ন পেমেন্ট', 'See all': 'সব দেখুন',
  'Nothing due soon.': 'শিগগিরই কিছু পরিশোধের নেই।', 'View all': 'সব দেখুন', 'No goals yet.': 'এখনও কোনো লক্ষ্য নেই।',
  'Paid {d}': '{d} তারিখে পরিশোধিত', 'Due {d} · paused': 'মেয়াদ {d} · বিরতিতে', 'Due {d} · not fully covered': 'মেয়াদ {d} · পুরো টাকা নেই',
  'Estimate · higher in summer · due {d}': 'অনুমান · গ্রীষ্মে বেশি · মেয়াদ {d}', 'Due {d} · pays on due date': 'মেয়াদ {d} · নির্ধারিত দিনে পরিশোধ হবে',
  'This is a forecast made when your last transfer arrived. It looks at how often and how much your sender usually sends, the time of year, and recent delays.': 'আপনার সর্বশেষ ট্রান্সফার আসার সময় এই পূর্বাভাস তৈরি হয়েছে। এতে প্রেরক সাধারণত কত ঘন ঘন ও কত টাকা পাঠান, বছরের সময় এবং সাম্প্রতিক দেরি বিবেচনা করা হয়।',
  'adds about {n} days': 'প্রায় {n} দিন যোগ করে', 'saves about {n} days': 'প্রায় {n} দিন কমায়', 'adds ~{n} days': 'প্রায় {n} দিন যোগ করে', 'saves ~{n} days': 'প্রায় {n} দিন কমায়',
  'A simple “same as last time” guess would say {n} days and {amt}.': 'শুধু “আগের বারের মতো” ধরলে বলত {n} দিন এবং {amt}।',
  'If the transfer is late, the range is widened instead of pretending the forecast still holds.': 'ট্রান্সফার দেরি হলে পূর্বাভাস ঠিক আছে ভান না করে পরিসর বাড়ানো হয়।',
  'We take the money you can spend, subtract bills that are not yet covered ({amt}), and divide by the days until your next transfer is likely to arrive, leaning toward the later end so a late transfer does not catch you out.': 'আপনার খরচযোগ্য টাকা থেকে এখনও সংরক্ষিত নয় এমন বিল ({amt}) বাদ দিয়ে পরবর্তী ট্রান্সফার আসার সম্ভাব্য দিন দিয়ে ভাগ করা হয়; দেরির দিকটা বেশি ধরা হয় যাতে ট্রান্সফার দেরিতে এলেও সমস্যা না হয়।',
  'It is a guide, not a limit. You decide what to spend.': 'এটি একটি দিকনির্দেশনা, সীমা নয়। কী খরচ করবেন তা আপনি ঠিক করবেন।',
  'Why this estimate': 'এই অনুমান কেন',
  // remittance modal
  'Money received': 'টাকা এসেছে', 'from {who} · {city} · {d}': '{who} · {city} · {d}', 'Suggested split': 'প্রস্তাবিত ভাগ', 'Reserved first': 'আগে সংরক্ষিত',
  'Daily needs': 'দৈনিক প্রয়োজন', 'Covers ~{n} days': 'প্রায় {n} দিন চলবে', 'Emergency fund': 'জরুরি তহবিল', 'Now {n} months saved': 'এখন {n} মাসের সঞ্চয়',
  'Nothing this time': 'এবার কিছু নয়', 'Goal: {name}': 'লক্ষ্য: {name}', '{n}% of target': 'লক্ষ্যের {n}%',
  'Based on your next transfer expected in {a}–{b} days, {bills}{emi} due before then. You can adjust any amount.': 'পরবর্তী ট্রান্সফার {a}–{b} দিনের মধ্যে আসার কথা, তার আগে {bills}{emi} পরিশোধ করতে হবে। যেকোনো পরিমাণ আপনি বদলাতে পারেন।',
  '{n} bill': '{n}টি বিল', '{n} bills': '{n}টি বিল', ' and {n} EMI': ' এবং {n}টি কিস্তি',
  'Chance of running short with this split:': 'এই ভাগে টাকা কম পড়ার সম্ভাবনা:', 'Why this split?': 'এই ভাগ কেন?',
  'Anything not assigned stays with you as spendable money.': 'যা বরাদ্দ করা হয়নি তা আপনার খরচযোগ্য টাকা হিসেবে থাকবে।',
  'These are suggestions. The decision is yours.': 'এগুলো পরামর্শ মাত্র। সিদ্ধান্ত আপনার।',
  'Use my amounts': 'আমার পরিমাণ ব্যবহার করুন', 'Accept plan': 'পরিকল্পনা গ্রহণ করুন', 'Adjust amounts': 'পরিমাণ বদলান', 'Cancel adjusting': 'বদলানো বাতিল', 'Skip for now': 'এখনের জন্য বাদ দিন',
  // payments
  'EMIs and bills on auto-pay': 'অটো-পে-তে থাকা কিস্তি ও বিল', 'Pause all': 'সব বিরতি দিন', '+ Add': '+ যোগ করুন', payment: 'পেমেন্ট', 'Bill vault': 'বিল ভল্ট',
  '{n}% reserved': '{n}% সংরক্ষিত', 'of {amt} due this month': 'এই মাসে মোট {amt} পরিশোধযোগ্য', 'Unusual bill detected': 'অস্বাভাবিক বিল ধরা পড়েছে',
  '{name} bill {amt} is {x}× your usual amount': '{name} বিল {amt}, যা আপনার স্বাভাবিক পরিমাণের {x} গুণ',
  'Usual range {a} – {b} over the last 6 months. ': 'গত ৬ মাসে স্বাভাবিক পরিসর {a} – {b}। ', 'Usual amount about {amt}. ': 'স্বাভাবিক পরিমাণ প্রায় {amt}। ',
  'Auto-pay is paused until you decide.': 'আপনি সিদ্ধান্ত না নেওয়া পর্যন্ত অটো-পে বন্ধ আছে।', 'Approve & pay': 'অনুমোদন ও পরিশোধ', Dispute: 'আপত্তি জানান', 'Pay manually': 'নিজে পরিশোধ করুন',
  'Auto-pay': 'অটো-পে', 'Auto-pay mandates': 'অটো-পে নির্দেশনা', '{n} active': '{n}টি চালু', Manage: 'পরিচালনা', 'No payments set up yet.': 'এখনও কোনো পেমেন্ট সেট করা হয়নি।',
  ' · limit {amt}': ' · সীমা {amt}', M: 'সো', T: 'ম', W: 'বু', F: 'শু', S: 'শ', 'Why was the {name} bill flagged?': '{name} বিলটি কেন চিহ্নিত হলো?',
  'Billed:': 'বিল হয়েছে:', 'Usual estimate:': 'স্বাভাবিক অনুমান:', '(same month last year). That is': '(গত বছরের একই মাস)। অর্থাৎ এটি', 'higher; we hold anything above 1.8× for your review.': 'বেশি; ১.৮ গুণের বেশি যেকোনো বিল আমরা আপনার যাচাইয়ের জন্য আটকে রাখি।',
  'If you dispute it, we assume it is corrected to the estimate before payment (a demo assumption).': 'আপনি আপত্তি জানালে ধরা হয় পরিশোধের আগে বিলটি অনুমানের পরিমাণে সংশোধিত হয়েছে (ডেমোর একটি ধারণা)।',
  'Due {d}': 'মেয়াদ {d}', 'variable bill': 'পরিবর্তনশীল বিল', 'fixed amount': 'নির্দিষ্ট পরিমাণ', 'Auto-pay on due date': 'নির্ধারিত দিনে অটো-পে',
  'Monthly limit:': 'মাসিক সীমা:', none: 'নেই', 'asks you to confirm above it': 'এর বেশি হলে আপনার নিশ্চিতকরণ চাইবে', 'no confirmation': 'নিশ্চিতকরণ লাগবে না',
  'Cancel this mandate': 'এই নির্দেশনা বাতিল করুন', 'Pausing keeps the bill on your list. You pay it yourself.': 'বিরতি দিলে বিলটি তালিকায় থাকে। আপনি নিজে পরিশোধ করেন।',
  'Manage auto-pay': 'অটো-পে পরিচালনা', 'usual {amt} · due day {n}': 'স্বাভাবিক {amt} · মেয়াদের দিন {n}', 'Add payment': 'পেমেন্ট যোগ করুন', Biller: 'বিলের প্রতিষ্ঠান',
  'e.g. Water supply, Bike EMI': 'যেমন: পানির বিল, বাইকের কিস্তি', Type: 'ধরন', Utility: 'ইউটিলিটি', 'EMI / loan': 'কিস্তি / ঋণ', School: 'স্কুল',
  'Due day (1–28)': 'মেয়াদের দিন (১–২৮)', 'Account / customer number': 'অ্যাকাউন্ট / গ্রাহক নম্বর', 'Usual amount ৳': 'স্বাভাবিক পরিমাণ ৳', 'Monthly limit ৳': 'মাসিক সীমা ৳',
  'Ask me to confirm payments over the limit': 'সীমার বেশি পেমেন্টে আমার নিশ্চিতকরণ চান', 'Set up auto-pay': 'অটো-পে চালু করুন', 'Demo only: no real account or money is connected.': 'শুধু ডেমো: কোনো আসল অ্যাকাউন্ট বা টাকা যুক্ত নেই।',
  // plan
  'Cash flow until your next transfer': 'পরবর্তী ট্রান্সফার পর্যন্ত নগদ প্রবাহ', 'Projected balance': 'সম্ভাব্য ব্যালেন্স',
  'We simulate hundreds of possible futures for your daily spending and show the middle path with a shaded range (10th to 90th percentile). Bills and EMIs are paid from your bill vault first and appear as dots.': 'আপনার দৈনিক খরচের শত শত সম্ভাব্য ভবিষ্যৎ আমরা সিমুলেট করি এবং ছায়াযুক্ত পরিসরসহ মাঝের পথটি দেখাই (১০ থেকে ৯০ শতাংশ)। বিল ও কিস্তি আগে বিল ভল্ট থেকে পরিশোধ হয় এবং বিন্দু হিসেবে দেখা যায়।',
  'Where the line dips below zero it turns red: that is when you could run short.': 'রেখা শূন্যের নিচে নামলে লাল হয়ে যায়: তখনই টাকা কম পড়তে পারে।',
  'Choose how to avoid the shortfall': 'ঘাটতি এড়াতে একটি উপায় বেছে নিন', 'The AI found {n} way to stay above zero. You decide.': 'এআই শূন্যের ওপরে থাকার {n}টি উপায় পেয়েছে। সিদ্ধান্ত আপনার।',
  'The AI found {n} ways to stay above zero. You decide.': 'এআই শূন্যের ওপরে থাকার {n}টি উপায় পেয়েছে। সিদ্ধান্ত আপনার।', 'Apply choice': 'পছন্দ প্রয়োগ করুন',
  'Good choice: aim to spend about {amt} less per day until the transfer arrives. We will keep watching.': 'ভালো সিদ্ধান্ত: ট্রান্সফার আসা পর্যন্ত দিনে প্রায় {amt} কম খরচ করার চেষ্টা করুন। আমরা নজর রাখব।',
  '{who} has been asked. It is their decision.': '{who}-কে জিজ্ঞাসা করা হয়েছে। সিদ্ধান্ত তাঁর।', 'Moved. You can top the goals up later.': 'সরানো হয়েছে। পরে লক্ষ্যগুলোতে আবার টাকা যোগ করতে পারবেন।',
  'You are on track': 'আপনি সঠিক পথে আছেন', 'No shortfall is expected if your next transfer arrives on time. We will tell you early if that changes.': 'পরবর্তী ট্রান্সফার সময়মতো এলে কোনো ঘাটতির আশঙ্কা নেই। অবস্থা বদলালে আমরা আগেই জানাব।',
  'Spending this month': 'এই মাসের খরচ', "Categories are simulated shares of each household's spending (an assumption), plus the bills you actually paid in the last 30 days.": 'ক্যাটাগরিগুলো প্রতিটি পরিবারের খরচের সিমুলেটেড অংশ (একটি ধারণা), সঙ্গে গত ৩০ দিনে আপনার আসলে পরিশোধ করা বিল।',
  'Last 30 days.': 'গত ৩০ দিন।', 'Coming up before next transfer': 'পরবর্তী ট্রান্সফারের আগে যা আসছে', ' (estimate)': ' (অনুমান)', 'Remittance from {who}': '{who}-এর রেমিট্যান্স', 'Nothing coming up.': 'আসন্ন কিছু নেই।',
  // goals
  'Saving together with {who}': '{who}-এর সঙ্গে একসঙ্গে সঞ্চয়', 'Saving together, step by step': 'একসঙ্গে, ধাপে ধাপে সঞ্চয়', '+ New goal': '+ নতুন লক্ষ্য', 'Saved toward goals': 'লক্ষ্যের জন্য জমা',
  'across {n} goal': '{n}টি লক্ষ্যে', 'across {n} goals': '{n}টি লক্ষ্যে', 'Planned each month': 'প্রতি মাসের পরিকল্পনা', 'at your recent pace': 'আপনার সাম্প্রতিক গতিতে',
  'Shared with {who}': '{who}-এর সঙ্গে শেয়ার করা', '{n} goal': '{n}টি লক্ষ্য', '{n} goals': '{n}টি লক্ষ্য', 'progress only': 'শুধু অগ্রগতি', '{a} of {b}': '{b}-এর মধ্যে {a}',
  Target: 'লক্ষ্যমাত্রা', 'Monthly plan': 'মাসিক পরিকল্পনা', '{amt} / month': '{amt} / মাস', 'Behind · add {amt}/month to catch up': 'পিছিয়ে · ধরতে মাসে {amt} যোগ করুন',
  'On track · at this pace, {n} month': 'সঠিক পথে · এই গতিতে {n} মাস', 'On track · at this pace, {n} months': 'সঠিক পথে · এই গতিতে {n} মাস', 'Private to family': 'শুধু পরিবারের জন্য',
  'Add money': 'টাকা যোগ করুন', Remove: 'সরান', 'Thinking of a new goal? Based on your forecast, about {amt} a month is realistic without risking bills.': 'নতুন লক্ষ্যের কথা ভাবছেন? আপনার পূর্বাভাস অনুযায়ী বিল ঝুঁকিতে না ফেলে মাসে প্রায় {amt} বাস্তবসম্মত।',
  'Needs about {amt} per transfer.': 'প্রতি ট্রান্সফারে প্রায় {amt} লাগবে।', 'Sharing with {who}': '{who}-এর সঙ্গে শেয়ারিং',
  'Invite your sender: they create a Sender account with this code': 'প্রেরককে আমন্ত্রণ জানান: তিনি এই কোড দিয়ে প্রেরকের অ্যাকাউন্ট খুলবেন', Copied: 'কপি হয়েছে', Copy: 'কপি',
  '{who} sees goal progress only, never your transactions, unless you choose to share more. You can change this any time, and you can say no to any request.': '{who} শুধু লক্ষ্যের অগ্রগতি দেখেন, আপনি আরও শেয়ার করতে না চাইলে কখনও আপনার লেনদেন নয়। যেকোনো সময় এটি বদলাতে পারেন এবং যেকোনো অনুরোধে না বলতে পারেন।',
  'Sender link:': 'প্রেরকের সংযোগ:', 'accepted ✓': 'গৃহীত ✓', 'waiting for the sender to accept': 'প্রেরকের গ্রহণের অপেক্ষায়',
  'Goal progress (the goals switched on above)': 'লক্ষ্যের অগ্রগতি (ওপরে চালু করা লক্ষ্যগুলো)', 'Total savings': 'মোট সঞ্চয়', 'Bills & EMI status, and a suggested send-by date': 'বিল ও কিস্তির অবস্থা এবং পাঠানোর প্রস্তাবিত তারিখ',
  '{who} asked to see this': '{who} এটি দেখতে চেয়েছেন', 'Spending details are not shared in this demo.': 'এই ডেমোতে খরচের বিস্তারিত শেয়ার করা হয় না।', 'New goal': 'নতুন লক্ষ্য',
  'Goal name': 'লক্ষ্যের নাম', 'e.g. Education': 'যেমন: শিক্ষা', 'Target ৳': 'লক্ষ্যমাত্রা ৳', 'Days to deadline': 'সময়সীমা (দিন)', 'Suggested: {amt} a month': 'প্রস্তাব: মাসে {amt}',
  'Your goal needs about {amt} a month for this deadline.': 'এই সময়সীমার জন্য আপনার লক্ষ্যে মাসে প্রায় {amt} লাগবে।', 'About {n} months at that pace.': 'ওই গতিতে প্রায় {n} মাস লাগবে।',
  'No spare money is expected right now.': 'এই মুহূর্তে বাড়তি টাকা থাকার আশা নেই।', 'This deadline looks tight; consider a longer one.': 'এই সময়সীমা কম মনে হচ্ছে; আরও বেশি সময় রাখার কথা ভাবুন।',
  'Create goal': 'লক্ষ্য তৈরি করুন', 'Add money to {name}': '{name}-এ টাকা যোগ করুন', 'Available to move: {amt}': 'সরানোর মতো টাকা: {amt}', 'Amount ৳': 'পরিমাণ ৳', 'Move to goal': 'লক্ষ্যে সরান',
  // sender
  'Sender view': 'প্রেরকের দৃশ্য', 'Switch to family view': 'পরিবারের দৃশ্যে যান', 'Family view': 'পরিবারের দৃশ্য', 'Hi {name}': 'হ্যালো {name}',
  'Here is how your family is doing back home.': 'দেশে আপনার পরিবার কেমন আছে, তা এখানে দেখুন।', 'Here is how things look for your family back home this month.': 'এই মাসে দেশে আপনার পরিবারের অবস্থা কেমন, তা এখানে দেখুন।',
  'Accept the family link': 'পরিবারের সংযোগ গ্রহণ করুন', 'You only see what the family chooses to share. This protects trust and prevents monitoring of family spending.': 'পরিবার যা শেয়ার করতে চায়, আপনি শুধু তাই দেখবেন। এতে বিশ্বাস রক্ষা হয় এবং পরিবারের খরচ নজরদারি এড়ানো যায়।',
  'All bills & EMI covered this month': 'এই মাসের সব বিল ও কিস্তি সংরক্ষিত', '{n} payment at risk': '{n}টি পেমেন্ট ঝুঁকিতে', '{n} payments at risk': '{n}টি পেমেন্ট ঝুঁকিতে',
  '{n} bill is being reviewed by the family (unusual amount).': '{n}টি বিল পরিবার যাচাই করছে (অস্বাভাবিক পরিমাণ)।', '{n} bills are being reviewed by the family (unusual amount).': '{n}টি বিল পরিবার যাচাই করছে (অস্বাভাবিক পরিমাণ)।',
  '{a} of {b} paid · {c} scheduled from the bill vault': '{b}টির মধ্যে {a}টি পরিশোধিত · বিল ভল্ট থেকে {c}টি নির্ধারিত',
  'The family asked if an earlier transfer is possible. It is your decision.': 'পরিবার জানতে চেয়েছে আগে টাকা পাঠানো সম্ভব কি না। সিদ্ধান্ত আপনার।',
  'Not shared yet. The family decides what you can see.': 'এখনও শেয়ার করা হয়নি। আপনি কী দেখবেন তা পরিবার ঠিক করে।', 'Ask the family': 'পরিবারকে জিজ্ঞাসা করুন', 'Requested…': 'অনুরোধ করা হয়েছে…',
  'Send by {d}': '{d}-এর মধ্যে পাঠান', 'Sending about {amt} by {d} keeps every bill on time': '{d}-এর মধ্যে প্রায় {amt} পাঠালে সব বিল সময়মতো পরিশোধ হবে', ' and avoids a shortfall around {d}': ' এবং {d} নাগাদ ঘাটতি এড়ানো যাবে',
  'No rush': 'তাড়া নেই', 'Your family looks covered. The next transfer is expected around {d}. A transfer of about {amt} would keep things comfortable.': 'আপনার পরিবার নিরাপদ আছে। পরবর্তী ট্রান্সফার {d} নাগাদ আসার কথা। প্রায় {amt} পাঠালে অবস্থা স্বস্তিদায়ক থাকবে।',
  'Plan this transfer': 'এই ট্রান্সফার পরিকল্পনা করুন', '(Demo: no real money is sent.)': '(ডেমো: কোনো আসল টাকা পাঠানো হয় না।)', 'Shared goals': 'শেয়ার করা লক্ষ্য', 'No goals shared yet.': 'এখনও কোনো লক্ষ্য শেয়ার করা হয়নি।',
  'on track': 'সঠিক পথে', 'slightly behind': 'সামান্য পিছিয়ে', 'Family savings (shared with you):': 'পরিবারের সঞ্চয় (আপনার সঙ্গে শেয়ার করা):', 'Your recent transfers': 'আপনার সাম্প্রতিক ট্রান্সফার',
  'Split: bills {a} · needs {b} · savings {c}': 'ভাগ: বিল {a} · প্রয়োজন {b} · সঞ্চয় {c}',
  'You see goal progress and payment status only. Detailed spending stays private to your family unless they choose to share it.': 'আপনি শুধু লক্ষ্যের অগ্রগতি ও পেমেন্টের অবস্থা দেখেন। পরিবার শেয়ার করতে না চাইলে খরচের বিস্তারিত তাদের একান্ত থাকে।',
  'Goal progress': 'লক্ষ্যের অগ্রগতি', 'Bills & EMI status': 'বিল ও কিস্তির অবস্থা', '✓ shared': '✓ শেয়ার করা', 'requested…': 'অনুরোধ করা হয়েছে…', 'not shared': 'শেয়ার করা হয়নি', Ask: 'জিজ্ঞাসা',
  // insights
  '{m} summary': '{m} মাসের সারসংক্ষেপ', 'Download report': 'রিপোর্ট ডাউনলোড', 'Late fees avoided': 'এড়ানো বিলম্ব ফি', 'so far': 'এ পর্যন্ত', 'On-time payments': 'সময়মতো পরিশোধ', 'Emergency buffer': 'জরুরি তহবিল',
  mo: 'মাস', 'target 1 month of needs': 'লক্ষ্য ১ মাসের খরচ', 'Kept in wallet': 'ওয়ালেটে রাখা', 'beyond 24 hours': '২৪ ঘণ্টার পরেও', 'Why the next transfer looks like this': 'পরবর্তী ট্রান্সফার কেন এমন দেখাচ্ছে',
  "Each bar shows how much one factor moved the predicted wait for your next transfer, from the model's feature contributions. “Later” means it adds days; “earlier” means it saves days.": 'প্রতিটি দণ্ড দেখায় একটি বিষয় আপনার পরবর্তী ট্রান্সফারের অপেক্ষার পূর্বাভাস কতটা বদলেছে। “দেরি” মানে দিন বাড়ায়; “আগে” মানে দিন কমায়।',
  'Why we expect a shortfall': 'কেন ঘাটতির আশঙ্কা করছি', 'These are the reasons the early-warning check found. A bigger bar means a bigger effect.': 'আগাম সতর্কতা যাচাইয়ে এই কারণগুলো পাওয়া গেছে। বড় দণ্ড মানে বেশি প্রভাব।',
  'What following the plan could mean (simulated)': 'পরিকল্পনা মানলে কী হতে পারে (সিমুলেটেড)', 'Simulated, not measured.': 'সিমুলেটেড, পরিমাপ করা নয়।', 'Compliance is an assumption; a real pilot would measure it.': 'পরিকল্পনা মানার হার একটি ধারণা; বাস্তব পাইলটে এটি পরিমাপ করা হবে।',
  'If the family follows the plan in…': 'পরিবার যদি পরিকল্পনা মানে…', '{p} of cycles': '{p} চক্রে', 'Bills on time': 'সময়মতো বিল', 'Late fees / year': 'বছরে বিলম্ব ফি', 'Kept in wallet after 24h': '২৪ ঘণ্টা পর ওয়ালেটে রাখা',
  'Average of synthetic test households. Without a plan: {p} of bills on time.': 'কৃত্রিম টেস্ট পরিবারগুলোর গড়। পরিকল্পনা ছাড়া: {p} বিল সময়মতো।', '{name} bill: last {n} months and next month': '{name} বিল: গত {n} মাস ও আগামী মাস',
  'The estimate for the next bill uses the same month last year. On our synthetic data this is about 10% off on average, versus about 16% for “same as last month”.': 'পরবর্তী বিলের অনুমান গত বছরের একই মাস থেকে করা হয়। আমাদের কৃত্রিম তথ্যে গড়ে এটি প্রায় ১০% ভুল, আর “গত মাসের মতো” ধরলে প্রায় ১৬%।',
}
